/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as PacienteLoginRouteImport } from './routes/paciente/login'
import { Route as PacienteAppRouteImport } from './routes/paciente/app'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppPacientesIndexRouteImport } from './routes/app/pacientes.index'
import { Route as AppPacientesIdRouteImport } from './routes/app/pacientes.$id'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const PacienteLoginRoute = PacienteLoginRouteImport.update({
  id: '/paciente/login',
  path: '/paciente/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PacienteAppRoute = PacienteAppRouteImport.update({
  id: '/paciente/app',
  path: '/paciente/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPacientesIndexRoute = AppPacientesIndexRouteImport.update({
  id: '/pacientes/',
  path: '/pacientes/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPacientesIdRoute = AppPacientesIdRouteImport.update({
  id: '/pacientes/$id',
  path: '/pacientes/$id',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/demo': typeof DemoRoute
  '/entrar': typeof EntrarRoute
  '/login': typeof LoginRoute
  '/sobre': typeof SobreRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/paciente/app': typeof PacienteAppRoute
  '/paciente/login': typeof PacienteLoginRoute
  '/app/': typeof AppIndexRoute
  '/app/pacientes/$id': typeof AppPacientesIdRoute
  '/app/pacientes/': typeof AppPacientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/demo': typeof DemoRoute
  '/entrar': typeof EntrarRoute
  '/login': typeof LoginRoute
  '/sobre': typeof SobreRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/paciente/app': typeof PacienteAppRoute
  '/paciente/login': typeof PacienteLoginRoute
  '/app': typeof AppIndexRoute
  '/app/pacientes/$id': typeof AppPacientesIdRoute
  '/app/pacientes': typeof AppPacientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/demo': typeof DemoRoute
  '/entrar': typeof EntrarRoute
  '/login': typeof LoginRoute
  '/sobre': typeof SobreRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/paciente/app': typeof PacienteAppRoute
  '/paciente/login': typeof PacienteLoginRoute
  '/app/': typeof AppIndexRoute
  '/app/pacientes/$id': typeof AppPacientesIdRoute
  '/app/pacientes/': typeof AppPacientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/admin'
    | '/demo'
    | '/entrar'
    | '/login'
    | '/sobre'
    | '/auth/callback'
    | '/paciente/app'
    | '/paciente/login'
    | '/app/'
    | '/app/pacientes/$id'
    | '/app/pacientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/demo'
    | '/entrar'
    | '/login'
    | '/sobre'
    | '/auth/callback'
    | '/paciente/app'
    | '/paciente/login'
    | '/app'
    | '/app/pacientes/$id'
    | '/app/pacientes'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/admin'
    | '/demo'
    | '/entrar'
    | '/login'
    | '/sobre'
    | '/auth/callback'
    | '/paciente/app'
    | '/paciente/login'
    | '/app/'
    | '/app/pacientes/$id'
    | '/app/pacientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  DemoRoute: typeof DemoRoute
  EntrarRoute: typeof EntrarRoute
  LoginRoute: typeof LoginRoute
  SobreRoute: typeof SobreRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  PacienteAppRoute: typeof PacienteAppRoute
  PacienteLoginRoute: typeof PacienteLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/paciente/login': {
      id: '/paciente/login'
      path: '/paciente/login'
      fullPath: '/paciente/login'
      preLoaderRoute: typeof PacienteLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paciente/app': {
      id: '/paciente/app'
      path: '/paciente/app'
      fullPath: '/paciente/app'
      preLoaderRoute: typeof PacienteAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/pacientes/': {
      id: '/app/pacientes/'
      path: '/pacientes'
      fullPath: '/app/pacientes/'
      preLoaderRoute: typeof AppPacientesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/pacientes/$id': {
      id: '/app/pacientes/$id'
      path: '/pacientes/$id'
      fullPath: '/app/pacientes/$id'
      preLoaderRoute: typeof AppPacientesIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppPacientesIdRoute: typeof AppPacientesIdRoute
  AppPacientesIndexRoute: typeof AppPacientesIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppPacientesIdRoute: AppPacientesIdRoute,
  AppPacientesIndexRoute: AppPacientesIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  DemoRoute: DemoRoute,
  EntrarRoute: EntrarRoute,
  LoginRoute: LoginRoute,
  SobreRoute: SobreRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  PacienteAppRoute: PacienteAppRoute,
  PacienteLoginRoute: PacienteLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
